# Generated by Django 4.2 on 2024-02-26 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fund",
            name="aum_usd",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=16, null=True
            ),
        ),
        migrations.AlterField(
            model_name="fund",
            name="inception_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
