# Generated by Django 4.2 on 2024-02-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demo", "0002_alter_fund_aum_usd_alter_fund_inception_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fund",
            name="aum_usd",
            field=models.DecimalField(
                blank=True, decimal_places=0, max_digits=16, null=True
            ),
        ),
    ]
