# Generated by Django 4.2.10 on 2024-02-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("demo", "0003_alter_fund_aum_usd"),
    ]

    operations = [
        migrations.AlterField(
            model_name="fund",
            name="strategy",
            field=models.CharField(
                choices=[
                    ("Arbitrage", "Arbitrage"),
                    ("Global Macro", "Global Macro"),
                    ("Long/Short Equity", "Long/Short Equity"),
                ],
                max_length=64,
            ),
        ),
    ]
